### ISSUE TITLE
Upgrade project to angular release candidate

### ISSUE THREAD

**Issue by ghost** [schempy/angular2-typescript-webpack#5]
We're going to need to upgrade the project at some point to the latest and greatest.  The Angular2 team just released their first RC 2 days ago.

**Comment by anthony-pinskey** [comment]
Yes, an upgrade to RC2 would be great. This really provides a wonderful app structure!

**Comment by hermanfransen** [comment]
See my pull request, I upgraded it to RC.1

**Comment by schempy** [comment]
Updated to angular 2.0.0-rc.1
